image: docker:stable

stages:
  - build

bullseye:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-bullseye
  - docker image rm koha/koha-testing:master-bullseye
  only:
    - master@koha-community/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-buster
  - docker image rm koha/koha-testing:master-buster
  only:
    - master@koha-community/koha-testing-docker

stretch:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-stretch --no-cache --rm -f dists/stretch/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-stretch
  - docker tag  koha/koha-testing:master-stretch koha/koha-testing:master
  - docker push koha/koha-testing:master
  - docker image rm koha/koha-testing:master-stretch koha/koha-testing:master
  only:
    - master@koha-community/koha-testing-docker

jessie:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-jessie --no-cache --rm -f dists/jessie/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-jessie
  - docker image rm koha/koha-testing:master-jessie
  only:
    - master@koha-community/koha-testing-docker

xenial:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-xenial --no-cache --rm -f dists/xenial/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-xenial
  - docker image rm koha/koha-testing:master-xenial
  only:
    - 20.05@koha-community/koha-testing-docker

bionic:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-bionic --no-cache --rm -f dists/bionic/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-bionic
  - docker image rm koha/koha-testing:master-bionic
  only:
    - master@koha-community/koha-testing-docker

focal:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-focal --no-cache --rm -f dists/focal/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-focal
  - docker image rm koha/koha-testing:master-focal
  only:
    - master@koha-community/koha-testing-docker
