image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

##sid:
##  stage: build
##  script:
##  - docker build -t koha/koha-testing:23.05-sid --no-cache --rm -f dists/sid/Dockerfile .
##  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
##  - docker push koha/koha-testing:23.05-sid
##  - docker image rm koha/koha-testing:23.05-sid
##  only:
##    - 23.05@koha-community/koha-testing-docker

bookworm:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.05-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.05-bookworm
  - docker image rm koha/koha-testing:23.05-bookworm
  only:
    - 23.05@koha-community/koha-testing-docker

bullseye:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.05-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.05-bullseye
  - docker tag  koha/koha-testing:23.05-bullseye koha/koha-testing:master
  - docker push koha/koha-testing:23.05
  - docker image rm koha/koha-testing:23.05-bullseye
  only:
    - 23.05@koha-community/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.05-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.05-buster
  - docker image rm koha/koha-testing:23.05-buster
  only:
    - 23.05@koha-community/koha-testing-docker

#focal:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:23.05-focal --no-cache --rm -f dists/focal/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:23.05-focal
#  - docker image rm koha/koha-testing:23.05-focal
#  only:
#    - 23.05@koha-community/koha-testing-docker
#
#jammy:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:23.05-jammy --no-cache --rm -f dists/jammy/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:23.05-jammy
#  - docker image rm koha/koha-testing:23.05-jammy
#  only:
#    - 23.05@koha-community/koha-testing-docker
#
#lunar:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:23.05-lunar --no-cache --rm -f dists/lunar/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:23.05-lunar
#  - docker image rm koha/koha-testing:23.05-lunar
#  only:
#    - 23.05@koha-community/koha-testing-docker
#
# -----------------------------------
# armd64 jobs

bullseye-arm64v8:
  image: arm64v8/docker
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  tags:
    - arm64
  script:
  - docker build -t koha/koha-testing:23.05-bullseye-arm64v8 --no-cache --rm -f dists/arm64v8/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.05-bullseye-arm64v8
  - docker image rm koha/koha-testing:23.05-bullseye-arm64v8
  only:
    - 23.05@koha-community/koha-testing-docker

#focal-arm64v8:
#  image: arm64v8/docker
#  stage: build
#  variables:
#    DOCKER_TLS_CERTDIR: ""
#  tags:
#    - arm64
#  script:
#  - docker build -t koha/koha-testing:23.05-focal-arm64v8 --no-cache --rm -f dists/arm64v8/focal/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:23.05-focal-arm64v8
#  - docker image rm koha/koha-testing:23.05-focal-arm64v8
#  only:
#    - 23.05@koha-community/koha-testing-docker
