image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-bullseye
  - docker image rm kohaaloha/koha-testing:master-bullseye
  only:
    - master@mjames/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster
  - docker image rm kohaaloha/koha-testing:master-buster
  only:
    - master@mjames/koha-testing-docker

stretch:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-stretch --no-cache --rm -f dists/stretch/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-stretch
  - docker tag  kohaaloha/koha-testing:master-stretch kohaaloha/koha-testing:master
  - docker push kohaaloha/koha-testing:master
  - docker image rm kohaaloha/koha-testing:master-stretch kohaaloha/koha-testing:master
  only:
    - master@mjames/koha-testing-docker

xenial:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-xenial --no-cache --rm -f dists/xenial/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-xenial
  - docker image rm kohaaloha/koha-testing:master-xenial
  only:
    - master@mjames/koha-testing-docker

bionic:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-bionic --no-cache --rm -f dists/bionic/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-bionic
  - docker image rm kohaaloha/koha-testing:master-bionic
  only:
    - master@mjames/koha-testing-docker

focal:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-focal --no-cache --rm -f dists/focal/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-focal
  - docker image rm kohaaloha/koha-testing:master-focal
  only:
    - master@mjames/koha-testing-docker

groovy:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-groovy --no-cache --rm -f dists/groovy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-groovy
  - docker image rm kohaaloha/koha-testing:master-groovy
  only:
    - master@mjames/koha-testing-docker
