image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


buster-rpi:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-rpi --no-cache --rm -f dists/buster-rpi/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-rpi
  - docker image rm kohaaloha/koha-testing:master-buster-rpi
#  only:
#    - master@koha-community/koha-testing-docker


