#image: docker:stable
image: docker:19.03.0

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""
#  DOCKER_TLS_CERTDIR: "/certs"


services:
  - docker:19.03.0-dind
#  - docker:dind

before_script:
  - docker info

stages:
  - build

buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster
  - docker image rm kohaaloha/koha-testing:master-buster
  only:
    - dind-ka@mjames/koha-testing-docker
