image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

##sid:
##  stage: build
##  script:
##  - docker build -t koha/koha-testing:master-sid --no-cache --rm -f dists/sid/Dockerfile .
##  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
##  - docker push koha/koha-testing:master-sid
##  - docker image rm koha/koha-testing:master-sid
##  only:
##    - master@koha-community/koha-testing-docker
#
#bookworm:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:master-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-bookworm
#  - docker image rm koha/koha-testing:master-bookworm
#  only:
#    - master@koha-community/koha-testing-docker
#
#bullseye:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:master-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-bullseye
#  - docker tag  koha/koha-testing:master-bullseye koha/koha-testing:master
#  - docker push koha/koha-testing:master
#  - docker image rm koha/koha-testing:master-bullseye
#  only:
#    - master@koha-community/koha-testing-docker
#
buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:23.05-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:23.05-buster
  - docker image rm koha/koha-testing:23.05-buster
  only:
    - 23.05@koha-community/koha-testing-docker
#
#focal:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:master-focal --no-cache --rm -f dists/focal/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-focal
#  - docker image rm koha/koha-testing:master-focal
#  only:
#    - master@koha-community/koha-testing-docker
#
#jammy:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:master-jammy --no-cache --rm -f dists/jammy/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-jammy
#  - docker image rm koha/koha-testing:master-jammy
#  only:
#    - master@koha-community/koha-testing-docker
#
#lunar:
#  stage: build
#  script:
#  - docker build -t koha/koha-testing:master-lunar --no-cache --rm -f dists/lunar/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-lunar
#  - docker image rm koha/koha-testing:master-lunar
#  only:
#    - master@koha-community/koha-testing-docker
#
## -----------------------------------
## armd64 jobs
#
#bullseye-arm64v8:
#  image: arm64v8/docker
#  stage: build
#  variables:
#    DOCKER_TLS_CERTDIR: ""
#  tags:
#    - arm64
#  script:
#  - docker build -t koha/koha-testing:master-bullseye-arm64v8 --no-cache --rm -f dists/arm64v8/bullseye/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-bullseye-arm64v8
#  - docker image rm koha/koha-testing:master-bullseye-arm64v8
#  only:
#    - master@koha-community/koha-testing-docker
#
#focal-arm64v8:
#  image: arm64v8/docker
#  stage: build
#  variables:
#    DOCKER_TLS_CERTDIR: ""
#  tags:
#    - arm64
#  script:
#  - docker build -t koha/koha-testing:master-focal-arm64v8 --no-cache --rm -f dists/arm64v8/focal/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push koha/koha-testing:master-focal-arm64v8
#  - docker image rm koha/koha-testing:master-focal-arm64v8
#  only:
#    - master@koha-community/koha-testing-docker
