image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

bookworm:
  stage: build
  script:
  - docker build -t koha/koha-testing:exp-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:exp-bookworm
  - docker tag  koha/koha-testing:exp-bookworm koha/koha-testing:exp
  - docker push koha/koha-testing:exp
  - docker image rm koha/koha-testing:exp-bookworm
  only:
    - exp@koha-community/koha-testing-docker
