image: docker:stable
#image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build

buster-common:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-common --no-cache --rm -f dists/buster-common/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-common
  - docker image rm kohaaloha/koha-testing:master-buster-common
  only:
    - master-ka-full@mjames/koha-testing-docker

buster-full:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-full --no-cache --rm -f dists/buster-full/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-full
  - docker image rm kohaaloha/koha-testing:master-buster-full
  only:
    - master-ka-full@mjames/koha-testing-docker

buster-core:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-core --no-cache --rm -f dists/buster-core/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-core
  - docker image rm kohaaloha/koha-testing:master-buster-core
  only:
    - master-ka-full@mjames/koha-testing-docker

# -----------------------

bullseye-common:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-bullseye-common --no-cache --rm -f dists/bullseye-common/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-bullseye-common
  - docker image rm kohaaloha/koha-testing:master-bullseye-common
  only:
    - master-ka-full@mjames/koha-testing-docker

# -------------------------------

buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster
  - docker image rm kohaaloha/koha-testing:master-buster
  only:
    - master-ka-full@mjames/koha-testing-docker

stretch-common:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-stretch-common --no-cache --rm -f dists/stretch-common/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-stretch-common
  - docker image rm kohaaloha/koha-testing:master-stretch-common
  only:
    - master-ka-full@mjames/koha-testing-docker


