image: kohaaloha/koha-testing:master-buster

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - test

buster:
  stage: test
  script:
  - export RUN_TESTS_AND_EXIT="yes"
  - export SYNC_REPO=./koha-dev.git
  - export LOCAL_USER_ID=$(id -u)
  - export COVERAGE=$COVERAGE
  - export KOHA_IMAGE="master-stretch"
  - export KOHA_BRANCH="20.05"
  - git clone fetch https://gitlab.com/mjames/koha-dev.git --depth=1 
  - rm -rf cover_db
  - # Fetch docker-compose.yml until it is included on the source tree
  - wget -O docker-compose.yml https://gitlab.com/mjames/koha-testing-docker/-/raw/master-ka/docker-compose.yml
  - wget -O docker-compose.mariadb_d9.yml    https://gitlab.com/mjames/koha-testing-docker/-/raw/master-ka/docker-compose.mariadb_d10.yml
  - mkdir -p env
  - wget -O env/defaults.env   https://gitlab.com/mjames/koha-testing-docker/-/raw/master-ka/env/defaults.env
  - cp env/defaults.env .env
  - docker-compose pull
  - docker-compose -f docker-compose.yml -f docker-compose.mariadb_d9.yml -p koha up --abort-on-container-exit --no-color --force-recreate
  - docker-compose down
  only:
    - master-ka2@mjames/koha-testing-docker
