image: docker:stable
#image: docker:19.03.0-dind
#image: docker:stable-dind-rootless

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""
#  DOCKER_TLS_CERTDIR: "/certs"


services:
#  - docker:stable-dind
#  - docker:stable-dind-rootless
#  - docker:19.03.0-dind
#  - docker:dind

before_script:
#  - docker info
  - whoami

stages:
  - build

buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:dind1  --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:dind1
  - docker image rm kohaaloha/koha-testing:dind1
  only:
    - dind-ka@mjames/koha-testing-docker
  allow_failure: true
