image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

bookworm:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-bookworm
  - docker image rm koha/koha-testing:21.05-bookworm
  only:
    - 21.05@koha-community/koha-testing-docker

bullseye:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-bullseye
  - docker image rm koha/koha-testing:21.05-bullseye
  only:
    - 21.05@koha-community/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-buster
  - docker image rm koha/koha-testing:21.05-buster
  only:
    - 21.05@koha-community/koha-testing-docker

stretch:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-stretch --no-cache --rm -f dists/stretch/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-stretch
  - docker tag  koha/koha-testing:21.05-stretch koha/koha-testing:21.05
  - docker push koha/koha-testing:21.05
  - docker image rm koha/koha-testing:21.05-stretch koha/koha-testing:21.05
  only:
    - 21.05@koha-community/koha-testing-docker

xenial:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-xenial --no-cache --rm -f dists/xenial/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-xenial
  - docker image rm koha/koha-testing:21.05-xenial
  only:
    - 21.05@koha-community/koha-testing-docker

bionic:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-bionic --no-cache --rm -f dists/bionic/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-bionic
  - docker image rm koha/koha-testing:21.05-bionic
  only:
    - 21.05@koha-community/koha-testing-docker

focal:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-focal --no-cache --rm -f dists/focal/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-focal
  - docker image rm koha/koha-testing:21.05-focal
  only:
    - 21.05@koha-community/koha-testing-docker

jammy:
  stage: build
  script:
  - docker build -t koha/koha-testing:21.05-jammy --no-cache --rm -f dists/jammy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:21.05-jammy
  - docker image rm koha/koha-testing:21.05-jammy
  only:
    - 21.05@koha-community/koha-testing-docker
