image: docker:stable

stages:
  - build

buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:master-buster
  - docker image rm koha/koha-testing:master-buster
  only:
    - master@koha-community/koha-testing-docker
