image: docker:stable
#image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build

20.11-buster-full-tar:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:20.11-buster-full-tar --no-cache --rm -f dists/buster-full-tar/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:20.11-buster-full-tar
  - docker image rm kohaaloha/koha-testing:20.11-buster-full-tar
#  only:
#    - 20.11-buster-full-tar@mjames/koha-testing-docker


#20.11-fedora-full-tar:
#  stage: build
#  script:
#  - docker build -t kohaaloha/koha-testing:20.11-fedora-full-tar --no-cache --rm -f dists/fedora-full-tar/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push kohaaloha/koha-testing:20.11-fedora-full-tar
#  - docker image rm kohaaloha/koha-testing:20.11-fedora-full-tar
##  only:
##    - 20.11-fedora-full-tar@mjames/koha-testing-docker
#
