image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

#bullseye:
#  stage: build
#  script:
#  - docker build -t kohaaloha/koha-testing:master-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push kohaaloha/koha-testing:master-bullseye
#  - docker image rm kohaaloha/koha-testing:master-bullseye
##  only:
##    - master@kohaaloha/koha-testing-docker
#

buster-core:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-core --no-cache --rm -f dists/buster-core/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-core
  - docker image rm kohaaloha/koha-testing:master-buster-core
#  only:
#    - master@kohaaloha/koha-testing-docker

buster-full:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-full --no-cache --rm -f dists/buster-full/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-full
  - docker image rm kohaaloha/koha-testing:master-buster-full
#  only:
#    - master@kohaaloha/koha-testing-docker


