image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster
  - docker image rm kohaaloha/koha-testing:master-buster
#  only:
#    - master@koha-community/koha-testing-docker

hirsute:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-hirsute --no-cache --rm -f dists/hirsute/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-hirsute
  - docker image rm kohaaloha/koha-testing:master-hirsute
#  only:
#    - master@koha-community/koha-testing-docker

