image: docker:stable
#image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build


#buster:
#  stage: build
#  script:
#  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push kohaaloha/koha-testing:master-buster
#  - docker image rm kohaaloha/koha-testing:master-buster
#  only:
#    - master-ka@mjames/koha-testing-docker
#

ulyana:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-ulyana --no-cache --rm -f dists/ulyana/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-ulyana
  - docker image rm kohaaloha/koha-testing:master-ulyana
  only:
    - master-ka@mjames/koha-testing-docker

groovy:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-groovy --no-cache --rm -f dists/groovy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-groovy
  - docker image rm kohaaloha/koha-testing:master-groovy
  only:
    - master-ka@mjames/koha-testing-docker
