image: docker:stable
#image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build

bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-bullseye
  - docker image rm kohaaloha/koha-testing:master-bullseye
  only:
    - master-ka@mjames/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster
  - docker image rm kohaaloha/koha-testing:master-buster
  only:
    - master-ka@mjames/koha-testing-docker


buster-i386:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster-i386 --no-cache --rm -f dists/buster-i386/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster-i386
  - docker image rm kohaaloha/koha-testing:master-buster-i386
  only:
    - master-ka@mjames/koha-testing-docker


stretch:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-stretch --no-cache --rm -f dists/stretch/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-stretch
  - docker image rm kohaaloha/koha-testing:master-stretch
  only:
    - master-ka@mjames/koha-testing-docker

jessie:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-jessie --no-cache --rm -f dists/jessie/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-jessie
  - docker image rm kohaaloha/koha-testing:master-jessie
  only:
    - master-ka@mjames/koha-testing-docker

xenial:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-xenial --no-cache --rm -f dists/xenial/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-xenial
  - docker image rm kohaaloha/koha-testing:master-xenial
  only:
    - master-ka@mjames/koha-testing-docker

bionic:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-bionic --no-cache --rm -f dists/bionic/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-bionic
  - docker image rm kohaaloha/koha-testing:master-bionic
  only:
    - master-ka@mjames/koha-testing-docker

focal:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-focal --no-cache --rm -f dists/focal/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-focal
  - docker image rm kohaaloha/koha-testing:master-focal
  only:
    - master-ka@mjames/koha-testing-docker

groovy:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-groovy --no-cache --rm -f dists/groovy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-groovy
  - docker image rm kohaaloha/koha-testing:master-groovy
  only:
    - master-ka@mjames/koha-testing-docker

ulyana:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-ulyana --no-cache --rm -f dists/ulyana/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-ulyana
  - docker image rm kohaaloha/koha-testing:master-ulyana
  only:
    - master-ka@mjames/koha-testing-docker


