image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: 1

bookworm:
  stage: build
  script:
  - docker build -t koha/koha-testing:22.11-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:22.11-bookworm
  - docker image rm koha/koha-testing:22.11-bookworm
  only:
    - 22.11@koha-community/koha-testing-docker

bullseye:
  stage: build
  script:
  - docker build -t koha/koha-testing:22.11-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:22.11-bullseye
  - docker tag  koha/koha-testing:22.11-bullseye koha/koha-testing:22.11
  - docker push koha/koha-testing:22.11
  - docker image rm koha/koha-testing:22.11-bullseye
  only:
    - 22.11@koha-community/koha-testing-docker

buster:
  stage: build
  script:
  - docker build -t koha/koha-testing:22.11-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:22.11-buster
  - docker image rm koha/koha-testing:22.11-buster
  only:
    - 22.11@koha-community/koha-testing-docker

bionic:
  stage: build
  script:
  - docker build -t koha/koha-testing:22.11-bionic --no-cache --rm -f dists/bionic/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:22.11-bionic
  - docker image rm koha/koha-testing:22.11-bionic
  only:
    - 22.11@koha-community/koha-testing-docker

focal:
  stage: build
  script:
  - docker build -t koha/koha-testing:22.11-focal --no-cache --rm -f dists/focal/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:22.11-focal
  - docker image rm koha/koha-testing:22.11-focal
  only:
    - 22.11@koha-community/koha-testing-docker

jammy:
  stage: build
  script:
  - docker build -t koha/koha-testing:22.11-jammy --no-cache --rm -f dists/jammy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push koha/koha-testing:22.11-jammy
  - docker image rm koha/koha-testing:22.11-jammy
  only:
    - 22.11@koha-community/koha-testing-docker
