image: docker:stable
#image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

#services:
#  - docker:18-dind

stages:
  - build


buster:
  stage: build
  script:
  - docker build -t kohaaloha/koha-testing:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/koha-testing:master-buster
  - docker image rm kohaaloha/koha-testing:master-buster
  only:
    - master-ka@mjames/koha-testing-docker
