version: '3'
services:
    koha:
        image: kohaaloha/koha-testing:buster-arm64-hello
        cap_add:
            - ALL
              #        volumes:
              #            - ${SYNC_REPO}:/kohadevbox/koha
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
              #        environment:
                #            LOCAL_USER_ID: ${LOCAL_USER_ID}
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            kohanet:
        ports:
            - "8080:8080"
            - "8081:8081"

networks:
    kohanet:
