version: '3'
services:
    es:
        image: koha/elasticsearch-icu:opensearch-2.x
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - plugins.security.disabled=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - kohanet
