version: '3'
services:
    db:
        image: arm64v8/mariadb:10.5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: koha_kohadev
            MYSQL_USER: koha_kohadev
            MYSQL_PASSWORD: password
        networks:
            - kohanet
    es:
        image: kohaaloha/elasticsearch-icu-arm64:7.x
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - kohanet
    koha:
        image: koha/koha-testing:22.11-bullseye-arm64v8
        depends_on:
            - db
            - es
            - memcached
#            - selenium
        cap_add:
            - ALL
        volumes:
            - ${SYNC_REPO}:/kohadevbox/koha
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
        environment:
            COVERAGE: ${COVERAGE}
            CPAN: ${CPAN}
            RUN_TESTS_AND_EXIT: ${RUN_TESTS_AND_EXIT}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
            LIGHT_TEST_SUITE: ${LIGHT_TEST_SUITE}
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            kohanet:
                aliases:
                    - "${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}"
                    - "${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}"
        ports:
            - "8080:8080"
            - "8081:8081"
    memcached:
        image: arm64v8/memcached
        command: memcached -m 64m
        networks:
            - kohanet
#    selenium:
#        image: seleniarm/standalone-firefox:3
#        image: seleniarm/standalone-firefox:4.3.0-20220728
#        image: seleniarm/standalone-firefox
#
#        networks:
#            - kohanet
#        shm_size: 1gb

networks:
    kohanet:
