version: '3'
services:
    kibana:
        image: kibana-test
        build:
            context: ./kibana
        volumes:
            - "./kibana/config/:/usr/share/kibana/config"
        depends_on:
            - es
        networks:
            - kohanet
        ports:
            - "5601:5601"
    es:
        ports:
            - "9200:9200"
