alias ku='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -p koha up \
            --force-recreate'
alias ku-es6='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.es6.yml \
            -p koha up \
            --force-recreate'
alias ku-mdb='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.mariadb_latest.yml \
            -p koha up \
            --force-recreate'
alias ku-md9='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.mariadb_d9.yml \
            -p koha up \
            --force-recreate'
alias ku-md10='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.mariadb_d10.yml \
            -p koha up \
            --force-recreate'
alias ku-my8='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.mysql8.0.yml \
            -p koha up \
            --force-recreate'
alias kup='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.plugin.yml \
            -p koha up \
            --force-recreate'
alias kp='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.persistent.yml \
            -p koha up \
            --force-recreate'
alias kk='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.kibana.yml \
            -p koha up \
            --force-recreate'
alias kpk='cd "${KOHA_TESTING_DOCKER_HOME}"; \
          docker-compose \
            -f docker-compose.yml \
            -f docker-compose.persistent.yml \
            -f docker-compose.kibana.yml \
            -p koha up \
            --force-recreate'
alias kd='cd "${KOHA_TESTING_DOCKER_HOME}"; docker-compose -p koha down'
alias kshell="docker exec -it koha_koha_1 bash"
