#!/usr/bin/bash

export LANGUAGE='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

shopt -s histappend

# executable -> green
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Completion!
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Aliases :-D
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
# Load profile
if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile
fi

export PATH=${PATH}:/kohadevbox/bin

export EDITOR=${EDITOR}
export KOHA_CONF="/etc/koha/sites/${KOHA_INSTANCE}/koha-conf.xml"
export PERL5LIB=${PERL5LIB}
export KOHA_USER=${KOHA_USER}
export KOHA_PASS=${KOHA_PASS}
export KOHA_INTRANET_FQDN=${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}
export KOHA_INTRANET_URL=http://${KOHA_INTRANET_FQDN}:${KOHA_INTRANET_PORT}
export KOHA_OPAC_FQDN=${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}
export KOHA_OPAC_URL=http://${KOHA_OPAC_FQDN}:${KOHA_OPAC_PORT}
export PERL5LIB="/kohadevbox/koha:/kohadevbox/qa-test-tools"
export TEST_QA=1

PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]$(__git_ps1 "\[\e[1;33m\](%s)\[\e[0m\]")$ '
